# Generated by Django 4.1.3 on 2023-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.CharField(help_text='Придуманное описание пользователя', max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(help_text='Придуманый никнейм пользователя', max_length=30, null=True, verbose_name='Никнейм'),
        ),
    ]
