# Generated by Django 4.1.3 on 2023-01-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_users_description_users_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='memes',
            field=models.CharField(help_text='Список всех мемов пользователя', max_length=10000, null=True, verbose_name='мемы'),
        ),
        migrations.AddField(
            model_name='users',
            name='settings',
            field=models.BooleanField(default=True, help_text='Настройки пользователя (показывать / не показывать) свои мемы другим', verbose_name='настройки'),
        ),
    ]
