# Generated by Django 4.1.3 on 2023-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_users_memes_users_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favmemes',
            field=models.CharField(help_text='Избранные мемы пользователя', max_length=10000, null=True, verbose_name='избранное'),
        ),
    ]
