# Generated by Django 4.1.3 on 2023-02-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0005_memes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='favmemes',
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(help_text='ID Фотографии', max_length=10000, null=True, verbose_name='ID Фотографии')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_favorites', to='telebot.users', verbose_name='Пользователь')),
            ],
        ),
    ]
